### ISSUE TITLE
Corrode "doesn't handle yet" array initializers with static analysis

### ISSUE THREAD

**Issue by ghost** [jameysharp/corrode#119]
#include <stdio.h>

    int main()
    {
        char a[5] = {'a', 'b', 'c', 'd', '\0'};
        int i = 2;
        char b[i]; // doesn't handle this yet
        char c[1+1]; //doesn't handle this yet
        b[0] = 'x';
        c[0] = 'x';
        b[1] = '\0';
        c[1] = '\0';
        printf("a=%s\n", a);
        printf("b=%s\n", b);
        printf("c=%s\n", c);
        printf("i=%d\n", i);
        return 0;
    }

I would offer to write a PR, but I'm having trouble figuring out exactly what code path is actually being taken.

**Comment by jameysharp** [comment]
The declaration of `b` is technically a "variable-length array", because `i` is not a constant. Corrode may not support that for a while.

Today @ranweiler and I tried to make `c` work, at least, but there's a surprising amount going on there and we gave up for today.

This will get fixed eventually though, I promise. :-) Until then, I'm tracking these issues in #52.
