### ISSUE TITLE
irreducible control flow when compiling lzo

### ISSUE THREAD

**Issue by jrmuizel** [jameysharp/corrode#132]
The linked file https://pastebin.mozilla.org/9017940 fails to compile with a "irreducible control flow" message.

**Comment by jrmuizel** [comment]
It looks like the https://github.com/jameysharp/corrode/tree/wip-cfg branch is needed to fix this.

**Comment by jrmuizel** [comment]
However it looks like that branch doesn't work completely yet. I get errors like:
```
error[E0282]: unable to infer enough type information about `_`
  --> lzo1x_decompress_safe.rs:12:9
   |
12 |     let mut _currentBlock;
   |         ^^^^^^^^^^^^^^^^^ cannot infer type for `_`
   |
   = note: type annotations or generic parameter binding required
```

**Comment by jrmuizel** [comment]
FWIW, I manually made the control flow reducible in the c file and have published a crate around the converted code: https://crates.io/crates/rust-lzo

Thanks for making this possible.

**Comment by jameysharp** [comment]
Cool!

Well, I've merged the `wip-cfg` branch to master because it passes some reasonably extensive tests now, and my previous implementation had subtle but important bugs. I do need to make it skip emitting a let-binding for `_currentBlock` if the function is simple enough that that variable never becomes needed. Meanwhile, you can try just deleting that variable declaration in the output Corrode generates. If I do that, the code you pastebin'd translates to some Rust that looks correct.

Thanks for using Corrode! Pretty cool that you got it to spit out something good enough to use!
