### ISSUE TITLE
C language  va_list Error

### ISSUE THREAD

**Issue by meagon** [jameysharp/corrode#24]
corrode: ("/usr/lib/gcc/x86_64-linux-gnu/5/include/stdarg.h": line 40): illegal undefined type; check whether a real C compiler accepts this:
    __builtin_va_list

and stdarg.h line 40 is:

```
typedef __builtin_va_list __gnuc_va_list;
```

**Comment by jameysharp** [comment]
Yes, this is definitely a problem, especially since pretty much every C program includes something such as `stdio.h` that then includes `stdarg.h`!

I'm not sure what to do about it yet though. There was good discussion about this issue on [/r/rust: "dealing with va_list"](https://www.reddit.com/r/rust/comments/2qje69/ffi_dealing_with_va_list/).

Rust doesn't support implementing variadic ("varargs") functions, and that's the only way you can construct a `va_list`.

It would be nice to at least be able to pass around a `va_list` if some piece of external C code hands one to you, but as far as I can tell, C99 makes no guarantees about whether passing a `va_list` to a function is compatible with passing some generic type like `void*`.

That said, maybe we could get away with just treating it like `void*`. In [the x86-64 ABI](http://www.x86-64.org/documentation/abi.pdf) (section 3.5.7), for example, it's a length-1 array of a special struct. Because it's an array, when you pass a `va_list` to a function on x86-64, it's passed by reference, not copied by value, so treating it like `void*` should have the same ABI.

Here's a [Compiler Explorer](https://gcc.godbolt.org/) link for a [simple function that accepts a `va_list` and passes it through to another function](https://godbolt.org/g/38KEEf). (Note that I've carefully prevented it from tail-call optimizing.) Looking through the generated code on different architectures, none of them copy the `va_list`'s contents (except maybe ARM64 where I don't understand the generated code), so maybe all of them would be compatible with translating `__builtin_va_list` like `void *`?

So I guess at this point I've convinced myself to accept a patch that treats `__builtin_va_list` like `void*`, if someone wants to write one. I'd be happier about it if someone can find something in the C standard that justifies this translation.

**Comment by meagon** [comment]
Thank u,  will it support pass some errors to continue  translate c code to rust?

**Comment by jameysharp** [comment]
Do you mean, skipping over parts it can't handle and translating the rest? I hadn't thought about that. On the one hand, that would let Corrode handle a lot more source code than it can now, which seems good. On the other hand, it would be bad if something it didn't translate was important and nobody noticed it was missing.

I'd be happier if we could report errors lazily. If a source file doesn't use `va_list` in any of the functions it defines, then I don't particularly care whether that source file includes a header that defines `va_list`.
