### ISSUE TITLE
Can't translate basic C programs?

### ISSUE THREAD

**Issue by garethellis0** [jameysharp/corrode#25]
Everything that I try and translate seems to result it `pub unsafe fn main() -> i32 { 0i32 }` or something similar (depending on the types used in the c program). Why is this?

**Comment by jameysharp** [comment]
Thanks for trying Corrode! I'm not convinced I understand the problem you're encountering. Is this a duplicate of issue #20? If not, please provide a sample input that doesn't work and describe what you expected it to do.

**Comment by garethellis0** [comment]
If I have a simple c program, for example:

add.c
`
int add(int a, int b){
    return a+b;
}
`

and run 
`corrode add.c -Wall -lm`
I will get 
`#[no_mangle]
pub unsafe fn add(mut a : i32, mut b : i32) -> i32 { a + b }
`

I'm not very experience in c, but as far as I can tell that should be a completely valid program.

**Comment by jameysharp** [comment]
It appears to be working as designed, then. Could you explain what you
expected it to do instead?

**Comment by garethellis0** [comment]
Well. I feel like pretty stupid. For some reason I thought it was supposed to produce a file. Sorry about that.

**Comment by jameysharp** [comment]
You mean that you expected it to also run rustc to compile the generated
Rust to a binary? That's not a stupid thing to want, I'm just not sure how
to do it well yet. :-)

I'd like to have a wrapper around Corrode that you can use in place of GCC
or clang, because it would make it easier to do some of the testing I want
to do on existing projects with their complicated build systems.

I suspect doing this well involves looking at ccache/distcc to see how they
handle parsing arguments to find the specific ones they need.

The one suggestion I'd give you for future bug reports is to mention up
front what you expected to have happen and what actually happened. If you'd
said "I thought it was supposed to produce a compiled program but it just
printed some source code to the screen", I would have understood your
question more quickly. :-)

**Comment by garethellis0** [comment]
That's basically spot on. Thanks very much for the advice, looking forward to hopefully contributing.

**Comment by jameysharp** [comment]
I have a first step in this direction in commit 06a134f: Corrode now accepts any options that GCC does, and spits out Rust source in a file named like the input file but with the extension changed to `.rs`. It still does not run `rustc` for you, so it still isn't a replacement for a C compiler. But now you can try converting all the source files in a project with a command that's usually like `make CC=corrode`.
