### ISSUE TITLE
implement byteswap.h GCC builtins

### ISSUE THREAD

**Issue by jvns** [jameysharp/corrode#28]
I tried to run corrode on this program: https://github.com/tomhughes/libdwarf/blob/master/dwarfexample/simplereader.c

and got this error:

```
corrode: ("/usr/include/x86_64-linux-gnu/bits/byteswap.h": line 47): illegal undefined variable; check whether a real C compiler accepts this:
    __builtin_bswap32
```

I have no idea whether I'm correctly interpreting this error, but I thought I'd report it :)

**Comment by jameysharp** [comment]
You are interpreting it correctly!

It looks like `bswap32` should be translated to `i32::swap_bytes`, and similarly for other sizes. Fortunately this case can be done during variable lookup, so in `interpretExpr (CVar ...)` I guess, rather than needing to recognize larger function-call patterns to replace them with other idioms.

I would love to get a pull request implementing this! :smile: If you'd like help or advice, let me know!

**Comment by bnewbold** [comment]
I ran in to the same problem with different example code and hacked up a solution to the `__builtin_bswap32` problem, but it wasn't enough to make either @jvns code or mine compile in the end.

With this patch, both the libdwarf `dwarfexample/simplereader.c` and my example code now give something like:

```
bnewbold@eschaton$ corrode -I. -I. -I../libdwarf -I./../libdwarf simplereader.c
("simplereader.c": line 165): Corrode doesn't handle this yet:
    sizeof(localhash)
```

(there is a note/TODO about this in `src/Language/Rust/Corrode/C.md`)

(FWIW, my example code is the output C code from running `bnfc -m -c Calc.bnfc` on the example page from http://bnfc.digitalgrammars.com/)

**Comment by jameysharp** [comment]
Thank you for the pull request, @bnewbold! Looking at this situation again, I decided my original advice on how to solve it was not great, so I merged a different solution. But seeing your implementation revealed some details about the byte-swapping builtins that I hadn't considered, so my patch is really just a condensed version of the pattern you illustrated, which was super helpful. Thanks again!

I'm already tracking the issue you mentioned with `sizeof` in issue #13; perhaps you'd like to tackle that one? I've been avoiding doing it because I think it'll be a good introduction to the Corrode code base for somebody. But I'd very much like to see it get done because, as you've seen, `sizeof` applied to expressions is pretty widely used. It looks like that'll probably fix translation for 22 source files in the musl C library, for instance.
