### ISSUE TITLE
use current directory as include search directory

### ISSUE THREAD

**Issue by flip111** [jameysharp/corrode#34]
I run `corrode -Wall src/main.h` and it says it can not find file `src/version.h`. This is fixed with adding `-I.`, but it would be better to include the currect directory.

**Comment by jameysharp** [comment]
Thanks for this suggestion! Given what I know so far, though, I think Corrode is working as designed. The experiment you should try is:

Does running `gcc -Wall src/main.h` work on your example?

I expect you'll find that if Corrode requires an option like `-I.`, then so does GCC, since Corrode just runs `gcc` internally and passes along (most of) the arguments that you give it.

I'm closing this issue, but feel free to re-open it if you find that Corrode's behavior is different than GCC's.
