### ISSUE TITLE
does not build on Windows

### ISSUE THREAD

**Issue by cramertj** [jameysharp/corrode#45]
I get the following error running `cabal install` or `stack install` in the project root:

`cabal install` output:

```
Resolving dependencies...
Configuring corrode-0.1.0.0...
Building corrode-0.1.0.0...
Failed to install corrode-0.1.0.0
Build log ( C:\Users\crame\AppData\Roaming\cabal\logs\corrode-0.1.0.0.log ):
Building corrode-0.1.0.0...
Preprocessing library corrode-0.1.0.0...

src\Language\Rust\Corrode\C.lhs:1:1: error:
    File name does not match module name:
    Saw: `Main'
    Expected: `Language.Rust.Corrode.C'
cabal: Leaving directory '.'
cabal: Error: some packages failed to install:
corrode-0.1.0.0
```

`stack install` output:

```
corrode-0.1.0.0: build
Preprocessing library corrode-0.1.0.0...

C:\Users\crame\rustiness\corrode\src\Language\Rust\Corrode\C.lhs:1:1:
    File name does not match module name:
    Saw: `Main'
    Expected: `Language.Rust.Corrode.C'

--  While building package corrode-0.1.0.0 using:
      C:\Users\crame\AppData\Roaming\stack\setup-exe-cache\x86_64-windows\setup-Simple-Cabal-1.22.5.0-ghc-7.10.3.exe --builddir=.stack-work\dist\2672c1f3 build lib:corrode exe:corrode --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
```

This occurs on 64 bit Windows after a fresh install of the Haskell Platform.

**Comment by jameysharp** [comment]
That's odd. Thanks for reporting it!

If a Haskell module doesn't have a line saying `module ... where` at the beginning, then it's implicitly the `Main` module. But that source file _does_ have a module declaration. So I'm guessing it's one of these possibilities:
1. Maybe the symlink from `C.lhs` to `C.md` doesn't check out correctly when you clone the git repository on Windows. If you look at `C.lhs`, does it begin with the note that 'This is a "Literate Haskell" source file'?
2. Maybe the `markdown-unlit` preprocessor isn't running, or is failing silently. What happens if you run `markdown-unlit -h src\Language\Rust\Corrode\C.lhs src\Language\Rust\Corrode\C.lhs C.hs`? Does it write a `C.hs` file that has `module Language.Rust.Corrode.C` on one of its first few lines?

**Comment by cramertj** [comment]
Opening `C.lhs` in vim or Atom gives just the text `C.md`.  I'd bet the symlink is to blame. I didn't realize that file was supposed to be a symlink-- I thought it might just be some sort of hint to `stack` or `cabal` about where to find the appropriate information.

Running the `markdown-unlit` command produces a `C.hs` file at root level, but it's completely empty (as far as I can tell).

**Comment by jameysharp** [comment]
OK, yeah, it's Windows' lack of symlinks that's causing this build failure then. I'm just not sure yet what to _do_ about it. If I make the `.lhs` files be the real source files instead of just symlinks, then GitHub won't render them as Markdown.

For the moment, you can make progress by renaming `C.md` to `C.lhs` and, at top-level, `Main.md` to `Main.lhs`.

There's no reason in principle that Corrode shouldn't work on Windows, but there are probably more of these environmental differences that are going to crop up. Let's try to find a more complete list of Corrode's portability problems in parallel with thinking about how to fix this one.

**Comment by tamird** [comment]
reversing the symlink direction should make everyone happy. github will still follow the symlinks.

EDIT: i think.

**Comment by jameysharp** [comment]
@tamird: I seem to recall that GitHub didn't follow the symlink when I tried that a few weeks ago. Would you like to fork the repo and try it out? Maybe you can find the right magic. I would very much appreciate being proven wrong. :smile:

**Comment by cramertj** [comment]
Currently, github only shows `C.md` in [C.lhs](https://github.com/jameysharp/corrode/blob/master/src/Language/Rust/Corrode/C.lhs). Reversing the symlink would probably make `C.md` un-viewable on github.

**Comment by cramertj** [comment]
You could always just add a bit to the README to rename the file or to use one of the solutions given [here](https://stackoverflow.com/questions/5917249/git-symlinks-in-windows). Not an ideal solution, but it'd get people up and running.

**Comment by cramertj** [comment]
I got it to work after running [this script](https://github.com/openstreetmap/iD/blob/master/fixWinSymlinks.bat) with line 14 removed (since I was lazy and didn't want to copy the other script it calls). How would you feel about including the script in the project and adding a note to the README to run it before `stack install`/`cabal install`?

**Comment by jameysharp** [comment]
Good finds, @cramertj!

I'm confused though. You're saying you removed the `call :raiseUACIfNotAdmin` line?
1. Don't you need that call? I'm guessing from context that you have to have administrator privileges to run `mklink` (although [MSDN doesn't say so](https://technet.microsoft.com/en-us/library/cc753194%28v=ws.11%29.aspx)), and that line appears to be what switches the script to administrator mode if you aren't already there.
2. I don't see any external dependencies there; `raiseUACIfNotAdmin` is defined within the same script, and seems to generate the other script it needs into a temporary file as needed.

So, does the script work with line 14 still included? Or, alternatively, can you confirm that `mklink` works even when `net session` exits with an error because of not having administrator privileges?

Anyway, I would absolutely merge a pull request adding this script plus directions in the README on how to run it. Thanks for finding the right trick!

**Comment by cramertj** [comment]
It does in fact fail without admin permissions, but when I run with line 14 enabled I get the error `The system cannot find the batch label specified - raiseUACIfNotAdmin`. I'll look into it.

**Comment by cramertj** [comment]
Ah, it was a line endings issue-- I just ran `unix2dos` and that fixed it. Okay, I'll submit a PR!

**Comment by jameysharp** [comment]
Looks great, merged&mdash;thanks!

**Comment by hyperpape** [comment]
I had the same issue with having to run unix2dos to get the fixGitSymlinksForWindows.bat to run. I'm wondering if this merits changing the line endings in master, or adding a note to the readme?
