### ISSUE TITLE
fix initialization for enum-typed variables

### ISSUE THREAD

**Issue by jdub** [jameysharp/corrode#64]
In my ongoing quest to corrode `libsel4`, I have come across a new blocker. (I'm using `-DNDEBUG` to dodge `__FUNCTION__` for now.)

```
("libsel4/include/sel4/objecttype.h": line 23): Corrode doesn't handle this yet:
    seL4_NotificationObject
```

Here's what leads up to line 23 as per `gcc -E`:

``` c
#14 "libsel4/include/sel4/objecttype.h"
typedef enum api_object {
    seL4_UntypedObject,
    seL4_TCBObject,
    seL4_EndpointObject,
    seL4_NotificationObject,
    seL4_CapTableObject,
    seL4_NonArchObjectTypeCount,
} seL4_ObjectType;

__attribute__((deprecated("use seL4_NotificationObject"))) static const seL4_ObjectType seL4_AsyncEndpointObject = seL4_NotificationObject;
```

It's nothing to do with the `__attribute__`, as it aborts the same way without it.

So, could it be something to do with referencing an enum member (`seL4_NotificationObject`), but corrode doesn't keep enough state/context to know what's going on? (I recall from other issues that this crops up elsewhere.)

Related to #19, not fixed by #40?

**Comment by jameysharp** [comment]
Oh, whoops! This is specifically a problem with initializers for variables of `enum` type. I believe the immediate problem is this line:

``` haskell
zeroInitializer IsEnum{} = unimplemented initial
```

Whenever we have an initializer, we first construct the zero-equivalent initializer, and then override it with the user-specified initializer. This makes partial `struct` initialization easier. In this case the user-specified initializer fully specifies the desired contents of the variable, but unfortunately we've already given up before we even look at it.

I guess there are two choices for fixing this:
1. Figure out how to zero-initialize `enum` types. This option would work for this specific case but can't work in general, I think; not every `enum` has a value equivalent to 0.
2. Only add zero-initialized values to the internal `Initializer` representation if they're missing _after_ `translateInitList` and the like have run. This option doesn't fix cases where the `enum` really doesn't have an explicit initializer, but I guess I hope that's less common...

I think it's worth taking both approaches eventually, since they fail in different ways, but option 2 feels like the right one to do first.

**Comment by jdub** [comment]
Awesome, thank you! (And, as always, thank you for explaining things.)
