### ISSUE TITLE
__builtin_memcpy_chk

### ISSUE THREAD

**Issue by waywardmonkeys** [jameysharp/corrode#84]
Clang will convert some instances of calls to `memcpy` to `__builtin_memcpy_chk`.

I believe that passing `-fno-builtin` along should address this, but I'm not sure.

This results in an error like:

```
("rectset.c": line 50): illegal undefined variable; check whether a real C compiler
    accepts this:
    __builtin___memcpy_chk
```

from this C:

```c
  memcpy(rects, trs->rects, n * sizeof(trs->rects[0]));
```

**Comment by jameysharp** [comment]
Seems to me the long-term solution is going to be to stop using the system's C preprocessor, so we don't hit code paths that are specific to `__GNUC__` or `__GNUC_PREREQ` or whatever clang sets.

Translating `__builtin___memcpy_chk` will be a bit tricky, especially if it turns out that its argument list is not the same as for `memcpy`. (Which it looks like GCC's isn't, at least.) Best option is to find some way to avoid triggering that replacement in the preprocessor.

Would you check whether passing `-fno-builtin` helps? I'm guessing it won't, but if it does we should just always pass that.

**Comment by waywardmonkeys** [comment]
I passed `-fno-builtin` on the command line to `corrode`, but that didn't seem to do anything. I also tried out `-Wp,-fno-builtin` and by using `-v`, I saw that it was getting that argument, but it still failed in the same way.

**Comment by waywardmonkeys** [comment]
Okay, this happens because of this in `/usr/include/secure/string.h`:

``` c
#if __has_builtin(__builtin___memcpy_chk) || defined(__GNUC__)
#undef memcpy
#define memcpy(dest, src, len)          \
  __builtin___memcpy_chk (dest, src, len, __darwin_obsz0 (dest))
#endif
```

So, if `__has_builtin` is implemented correctly, then this wouldn't be an issue.

**Comment by waywardmonkeys** [comment]
Sorry, I misread that last block of code. Having a correct `__has_builtin` wouldn't help. But that block of code is the source of this problem.

**Comment by waywardmonkeys** [comment]
Okay, pass `-D_FORTIFY_SOURCE=0` to disable all of that stuff.

**Comment by jameysharp** [comment]
Ah, excellent! Would you like to put together a patch to automatically set that definition in Main.lhs?
