### ISSUE TITLE
clang: Better way to disable blocks support

### ISSUE THREAD

**Issue by waywardmonkeys** [jameysharp/corrode#85]
Right now, you're sort of disabling blocks by undefining `__BLOCKS__`. A better way to do this would be to pass `-fno-blocks` when it is `clang`.

**Comment by jameysharp** [comment]
That might be better, yes, if we can make it work.

I can't tell whether we're using clang, because Corrode always invokes `gcc`, but on OS X, that's actually clang. So we'd need to figure out whether GCC accepts `-fno-blocks` too.

As I mentioned elsewhere, doing the preprocessing step internally (instead of calling out to either GCC or clang) would let us fix all these kinds of issues reliably. But until then, we need a growing pile of kludges.

**Comment by jameysharp** [comment]
...and unfortunately, at least on "gcc (Debian 6.1.1-11) 6.1.1 20160802", I get:

```
gcc: error: unrecognized command line option ‘-fno-blocks’; did you mean ‘-fno-doc’?
```

So I don't see a way to pass `-fno-blocks` reliably, which means I think we're stuck with undefining `__BLOCKS__` until we have a more comprehensive solution for the preprocessing step.
