### ISSUE TITLE
Corrode doesn't handle sigset.h

### ISSUE THREAD

**Issue by phase** [jameysharp/corrode#97]
```
("/usr/include/x86_64-linux-gnu/bits/sigset.h": line 29): Corrode doesn't handle this yet:
    __val[1024 / (8 * sizeof(unsigned long int))]
```

The file I'm using is [o.c](https://github.com/phase/o/blob/master/o.c), but I presume it has something to do with [libregexp](https://github.com/0intro/libregexp).

**Comment by jameysharp** [comment]
Hi! Specifically, Corrode is failing here because at the moment it only supports arrays with known size where the size is given as an integer literal. So Corrode would have accepted `__val[32]`, for example, although that is only the right size on a system where `long` is 32-bit.

I'm still thinking about how to handle more general array declarations. Let's track this in the existing "arrays are broken" issue, #52.
